config/routes.rb
Rails.application.routes.draw do
  resources :samples
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resource :profile
    resources :samples
  end

  resources :contacts

  get '/about' => 'pages#about'
  
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :users
end

app/models/profile.rb
class	Profile < ActiveRecord::Base
	belongs_to :user

end

app/models/sample.rb
class Sample < ActiveRecord::Base
	belongs_to :user

	has_attached_file :img_before, styles: { carousel: "750x500#", large: "600x400#", medium: "300x200", small: "100x100#" }, :default_url => "no_image.png"
  validates_attachment_content_type :img_before, content_type: /\Aimage\/.*\Z/

  has_attached_file :img_after, styles: { carousel: "750x500#", large: "600x400#", medium: "300x200#", small: "100x100#" }, :default_url => "no_image.png"
  validates_attachment_content_type :img_after, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :plan
  has_one :profile
  has_many :samples

  attr_accessor :stripe_card_token

  def save_with_payment
  	if valid?
  		customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
  		self.stripe_customer_token = customer.id
  		save!
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
	  def configure_permitted_parameters
	  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
	  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new		
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)

		if @contact.save

			name = params[:contact][:name]
			email = params[:contact][:email]
			body = params[:contact][:comments]

			ContactMailer.contact_email(name, email, body).deliver
			
			flash[:success] = "Success! Message sent."
			redirect_to root_path

		else	

			flash[:error] = "Error occured. Message not sent. Name & Email Required."
			redirect_to new_contact_path

		end
	end

	private

		def contact_params
			params.require(:contact).permit(:name, :email, :comments)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@basic_plan 	= Plan.find(1)
		@pro_plan 		= Plan.find(2)
		
	end

	def about
		
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    # form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    @profile = Profile.new
  end
  
  def create 
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :company_name, :job_title, :phone_number, :contact_email, :description)
    end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:user_id, :category, :title, :img_before, :img_after, :description, :marquee)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :select_plan, only: :new


	def create
		super do |resource|
			if params[:plan]
				resource.plan_id = params[:plan]
				if resource.plan_id == 2
					resource.save_with_payment
				else
					resource.save
				end
			end
		end
		
	end

	private
		def select_plan
			unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
				flash[:notice] = "Please select a membership plan to sign up."
				redirect_to root_url
			end			
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find( params[:id] )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
  	current_page?(link_path) ? "active" : ""
 	end
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">

		<div class="brand-header">
			<h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
			<h2>Feedback</h2>
			<h4>How can we improve your experience?</h4>
		</div>
		
		<div class="jumbotron brand-body">
			<%= form_for @contact do |f| %>
				<div class="form-group">
					<%= f.label :name %>*
					<%= f.text_field :name, class: 'form-control' %>
				</div>

				<div class="form-group">
					<%= f.label :email %>*
					<%= f.email_field :email, class: 'form-control' %>
				</div>
				
				<div class="form-group">
					<%= f.label :comments %>
					<%= f.text_area :comments, class: 'form-control' %>
				</div>
				<div class="form-group">
					<i> * required field </i>
				</div>

				<%= f.submit "Submit", class: 'btn btn-brand'%>

			<% end %>

		</div>
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Work Gems</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, class: 'navbar-brand' do %>
        Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems
      <% end %>
      
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      
      <ul class="nav navbar-nav">
        <li class="<%= active_class(about_path) %>"><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <% if current_user.profile %>
            <li class="<%= active_class(user_path(current_user)) %>"><%= link_to "Profile", user_path(current_user) %></li>
          <% else %>
            <li class="<%= active_class(new_user_profile_path(current_user)) %>"><%= link_to "Create Profile", new_user_profile_path(current_user) %></li>
          <% end %>
          <li class="<%= active_class(user_samples_path(current_user)) %>"><%= link_to "Showcase", user_samples_path(current_user) %></li>
          <li class="<%= active_class(new_user_sample_path(current_user)) %>"><%= link_to "Upload Gem", new_user_sample_path(current_user) %></li>
        <% end %>

        <li class="<%= active_class(new_contact_path) %>"><%= link_to "Feedback", new_contact_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li></li>
        <% else %>
          <!-- <li class="<%= active_class(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path, method: :get %></li> -->
          <li class="<%= active_class(new_user_session_path) %>"><%= link_to "Login", new_user_session_path, method: :get%></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" id="flash">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">

		<div class="brand-header">
			<h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
			<h2>About Us</h2>
			<h4>Why we created this app.</h4>
		</div>
		
		<div class="jumbotron brand-body">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, repellat, facilis! Dolore alias sapiente, aperiam veniam excepturi, dolor doloremque quibusdam sunt laboriosam exercitationem cupiditate maxime odit, minus et molestias magnam!
		</div>
		
	</div>
</div>

app/views/pages/home.html.erb
<div class="brand-jumbotron text-center">
	<h1 class="display-3">Welcome to Work<i class="fa fa-diamond" aria-hidden="true"></i>Gems</h1>
	<h3>The easiest way to showcase the gems of your work.</h3>
</div>

<div class="row">
	<% if user_signed_in? %>
		<div class="col-md-6 text-center">
      <% if current_user.profile %>

        <h2 class="text-center">  
          <%= link_to user_path(current_user), class: 'btn brand-btn-home btn-block' do %>
            <h3><i class="fa fa-address-book-o"></i> Profile</h3>
          <% end %>
        </h2>

      <% else %>

        <h2 class="text-center">  
          <%= link_to new_user_profile_path(current_user), class: 'btn brand-btn-home btn-block' do %>
            <h3><i class="fa fa-user"></i> Create Profile</h3>
          <% end %>
        </h2>

      <% end %>

    </div>
    <div class="col-md-6 text-center">
        <h2 class="text-center">  
          <%= link_to user_samples_path(current_user), class: 'btn brand-btn-home btn-block' do %>
            <h3><i class="fa fa-th"></i> Showcase</h3>
          <% end %>
        </h2>
    </div>
    <div class="col-md-6 text-center">
        <h2 class="text-center">  
          <%= link_to new_user_sample_path(current_user), class: 'btn brand-btn-home btn-block' do %>
            <h3><i class="fa fa-camera"></i> Upload Gem</h3>
          <% end %>
        </h2>
    </div>
    <div class="col-md-6 text-center">
        <h2 class="text-center">  
          <%= link_to new_contact_path(current_user), class: 'btn brand-btn-home btn-block' do %>
            <h3><i class="fa fa-commenting"></i> Feedback</h3>
          <% end %>
        </h2>
    </div>
    


	<% else %>
		<div class="col-md-6">
			<div class="brand-header-plan">
				<h3><strong>Starter Plan</strong></h3>
				<h5>Sign up for free and get 2 categories.</h5>
			</div>
			<div class="brand-body-plan">
				<ul>
					<li>Create up to <strong>2</strong> categories</li>
					<li>Add up to <strong>10</strong> gems per category</li>
				</ul>
			</div>
			<div class="brand-footer-plan">
				<%= link_to "Sign up for FREE", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-brand btn-lg btn-block' %>
			</div>
		</div>

		<div class="col-md-6">
			<div class="brand-header-plan">
				<h3><strong>Pro Plan</strong></h3>
				<h5>Sign up for $10 per month and get unlimited categories.</h5>
			</div>
			<div class="brand-body-plan">
				<ul>
					<li>Create <strong>unlimited</strong> categories</li>
					<li>Add up to <strong>10</strong> gems per category</li>
				</ul>
			</div>
			<div class="brand-footer-plan">
				<%= link_to "Sign up for $10 per month", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-brand btn-lg btn-block' %>
			</div>
		</div>
	<% end %>
</div>

app/views/profiles/new.html.erb
<div class="row">
  
  <div class="col-md-10 col-md-offset-1">



    <div class="brand-header">
      <h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
      <h2>Create Your Profile</h2>
      <p>Fill out your profile information so you can show and share your information with prospects and clients.</p>
    </div>

    <div class="jumbotron brand-body">

			<%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, autofocus: true, placeholder: 'John',  class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, autofocus: true, placeholder: 'Doe', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :company_name %>
          <%= f.text_field :company_name, autofocus: true, placeholder: 'ABC Construction, Inc.', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :job_title %>
          <%= f.select :job_title, ['General Contractor', 'Owner/President','Project Manager'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, autofocus: true, placeholder: '(888) 555-1212', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, autofocus: true, placeholder: 'john.doe@abcconstruction.com', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, autofocus: true, placeholder: 'Add a brief description of what you do.' , class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-brand' %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/samples/_form.html.erb
<%= form_for(@sample, html: {multipart: true }) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :img_before, "Before Image" %><br>
    <%= f.file_field :img_before, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :img_after, "After Image" %><br>
    <%= f.file_field :img_after, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :marquee %><br>
    <%= f.check_box :marquee %>
  </div>

  <br>
  
  <div class="actions">
    <%= f.submit "Submit Gem", class: 'btn btn-brand'%>
  </div>
<% end %>

app/views/samples/edit.html.erb
<div class="row">
  
  <div class="col-md-10 col-md-offset-1">

    <div class="brand-header">
      <h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
      <h2>Editing Gem</h2>      
    </div>

    <div class="jumbotron brand-body"> 

      <%= render 'form' %>

      <br>

      <%= link_to 'Show', @sample %> |
			<%= link_to 'Back', samples_path %>

    </div>
  </div>
</div>

app/views/samples/index.html.erb
<div class="row">
  
  <div>

    <div class="brand-header">
      <h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
      <h2>Showcase</h2>      
    </div>

    <div class="container-fluid">
      <div class="col-sm-12">
        <div class="row">
          <div id="carousel-showcase-index" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target=""carousel-showcase-index" data-slide-to="0" class="active"></li>
              <li data-target=""carousel-showcase-index" data-slide-to="1"></li>
              <li data-target=""carousel-showcase-index" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= image_tag "Elliot_stairway_before.png" %>
                <div class="carousel-caption">
                  Before
                </div>
              </div>
              <div class="item">
                <%= image_tag "Elliot_stairway_after.png" %>
                <div class="carousel-caption">
                  Before
                </div>
              </div>
              <div class="item">
                <%= image_tag "external_home_before.jpg" %>
                <div class="carousel-caption">
                  Before
                </div>
              </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href=""carousel-showcase-index" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href=""carousel-showcase-index" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div> 
    </div>


    <div class="brand-body"> 

      <table class="container table-lined table-hover">
        <thead>
          <tr>
            <th><h4><strong>Category</strong></h4></th>
            <th><h4><strong>Title</strong></h4></th>
            <th><h4><strong>Description</strong></h4></th>
            <th><h4><strong>Marquee</strong></h4></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @samples.each do |sample| %>
            <tr>
              <td class="text-center"><%= sample.category %></td>
              <td><%= sample.title %></td>
              <td><%= sample.description %></td>
              <td class="text-center"><%= sample.marquee %></td>
              <td>         
                <%= link_to sample do %>
                  <i class="fa fa-diamond">
                <% end %>
              </td>
              <td>
                <%= link_to edit_sample_path(sample) do %>
                 <i class="fa fa-pencil">
                <% end %>
              </td>
              <td>
                <%= link_to sample, method: :delete, data: { confirm: 'Are you sure you want to delete?' }  do %>
                  <i class="fa fa-trash-o">  
                <% end %>  
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <div class="text-center">
        <%= link_to 'New Gem', new_sample_path, class: 'btn btn-brand' %>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/samples/new.html.erb
<div class="row">
  
  <div class="col-md-10 col-md-offset-1">

    <div class="brand-header">
      <h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
      <h2>Add New Gem</h2>      
    </div>

    <div class="jumbotron brand-body"> 

      <%= render 'form' %>

      <br>

      <%= link_to 'Back', samples_path %>

    </div>
  </div>
</div>

app/views/samples/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-12 text-center">
      <div class="row text-center">

      <div class="col-sm-6">
          <div class="row text-center brand-header-show">
            <h4>Before</h4>
          </div>
          <div class="row text-center brand-body-show">
            <%= image_tag @sample.img_before.url(:large), class: 'brand-image-show img-responsive img-rounded' %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="row text-center brand-header-show">
            <h4>After</h4>
          </div>
          <div class="row text-center brand-body-show">
            <%= image_tag @sample.img_after.url(:large), class: 'brand-image-show img-responsive img-rounded' %>
          </div>
        </div>

        <div class="col-sm-12">
          <div class="row brand-body">
            <h5><strong>Category: </strong> <%= @sample.category %></h5>
            <h5><strong>Title: </strong> <%= @sample.title %></h5>
            <h5><strong>Description: </strong> <%= @sample.description %></h5>

          </div>
        </div>

        <div class="col-sm-12">
          <div class="row">

            <div class="col-xs-4">
              <div class="row text-center">
                <%= link_to samples_path, class: 'brand-btn-home btn-block' do %>
                  <h4><i class="fa fa-paper-plane"></i> Send</h4>
                <% end %>
              </div>
            </div>
            
            <div class="col-xs-4">
              <div class="row text-center">
                <%= link_to edit_sample_path, class: 'brand-btn-home btn-block' do %>
                  <h4><i class="fa fa-pencil"></i> Edit</h4>
                <% end %>
              </div>
            </div>
            
            <div class="col-xs-4">
              <div class="row text-center">
                <%= link_to samples_path, class: 'brand-btn-home btn-block' do %>
                  <h4><i class="fa fa-hand-o-left"></i> Back</h4>
                <% end %>
              </div>
            </div> 

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row"> 
  <div class="col-md-10 col-md-offset-1 col-sm-12">

    <div class="brand-header">
      <h2><strong>Work<i class="fa fa-diamond" aria-hidden:"true"></i>Gems</strong></h2>
      <h2>Profile</h2>
    </div>

    <div class="row business-card">
  		<div class="col-md-4 text-center business-card-image">

				<%= image_tag("kevin.png", size: "250x350", alt: "User Profile Image") %>

			</div>
			<div class="col-md-8 text-center">
				<div>
					<%= image_tag("homebuilders_default.png", size: "150x100", alt: "User Logo Image") %>
				</div>
				<div>
					<h1><strong><%= @user.profile.company_name %></strong></h1>
				</div>				
				<div>
					<h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
				</div>
				<hr class="brand">
				<div>
					<h2><strong>Phone: </strong><%= @user.profile.phone_number %></h2>
				</div>
				<div>
					<h2><strong>Email: </strong><%= @user.profile.contact_email %></h2>
				</div>
				<hr class="brand">
				<div>
					<h3> <i>https://www.companywebsitelinkwillgohere.com</i> </h3>
				</div>


			</div>
		</div>

		<div class="text-center">
			<%= link_to 'Send', '#', class: 'btn btn-lg btn-brand' %>

			<%= link_to 'Edit', '#', class: 'btn btn-lg btn-brand' %>
		</div>

		<br>

	</div>
</div>